[package]
name = "twitch-chat"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
serde = { version = "1.0.217", features = ["derive"] }
toml = { version = "0.8.19", features = ["preserve_order"] }
